development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pe50ec0cda7ac81cbbfe66bdb8511149f072e793f4601fda102520d36142b9104@ec2-3-83-77-33.compute-1.amazonaws.com:12979
  channel_prefix: livescore_production
